import Link from "next/link";
import { ArrowRight, Check, Database, MessageCircle, ShieldCheck, Sparkles, Users, Megaphone } from "lucide-react";
import { researchSources, whatsappOptions } from "@/domain/proposal";

const pillars = [
  { icon: Megaphone, number: "01", title: "Atraer con intención", copy: "Anuncios en Facebook e Instagram que invitan al cliente a escribir a OLBOL. Registramos el origen para medir qué campañas producen oportunidades." },
  { icon: MessageCircle, number: "02", title: "Responder con contexto", copy: "WhatsApp Business oficial y un asesor que consulta el catálogo. El equipo toma el control cuando la decisión necesita atención humana." },
  { icon: Users, number: "03", title: "Dar seguimiento", copy: "Proponemos Yaku para organizar conversaciones, responsables y oportunidades. Si OLBOL prefiere un panel propio, desarrollamos un CRM básico dentro del DMS." },
];
const answers = [
  { question: "¿Cómo protegemos el WhatsApp de OLBOL?", answer: "Usamos WhatsApp Business Platform, la vía autorizada por Meta para integrar IA y CRM. Las conexiones no oficiales añaden riesgo de bloqueo. En el canal oficial respetamos permisos, plantillas y calidad; Meta puede restringir cuentas por incumplimientos.", tag: "Un compromiso responsable" },
  { question: "¿Qué pasa con el número que ya utiliza OLBOL?", answer: "Primero revisamos el estado del número y sus antecedentes. Evaluamos la coexistencia de la app y la API con el proveedor; si no es elegible, acordamos una migración antes de tocar el canal actual.", tag: "Continuidad del negocio" },
  { question: "¿Qué hace el CRM básico?", answer: "Yaku es nuestra primera opción. Validaremos sus APIs y bandeja de conversaciones. La alternativa es un CRM básico en el panel DMS con contactos, responsables, etapas, tareas e historial; su alcance se define con el equipo de OLBOL.", tag: "Una operación simple" },
  { question: "¿Qué incluye realmente esta demo?", answer: "Catálogo conceptual, asesor local, comparación, simulación de cuota, resumen de WhatsApp y consola CRM con datos ficticios. La conexión oficial, el inventario real y las campañas se implementan en el piloto.", tag: "Alcance claro" },
];

export default function DemoPage() {
  return <main className="demo-page">
    <section className="demo-hero"><div className="shell demo-hero__inner"><div><span className="demo-kicker"><span/> OLBOL / PROPUESTA COMERCIAL</span><h1>Más conversaciones. Mejor seguimiento.</h1><p>Una experiencia que conecta tu catálogo, WhatsApp y equipo comercial para acompañar al cliente desde el primer interés.</p><div className="demo-hero__actions"><Link href="/asesor" className="button-primary">Probar la experiencia <ArrowRight size={16}/></Link><a href="#solucion" className="button-light">Conocer la solución <ArrowRight size={16}/></a></div></div><div className="demo-hero__signal"><div className="demo-hero__signal-top"><span>PROPUESTA PARA OLBOL</span><span className="signal-dot"/></div><strong>De un anuncio a una oportunidad con responsable.</strong><div className="demo-hero__signal-line"><span/><span/><span/><span/></div><small>Demostración conceptual · Integración oficial en el piloto</small></div></div></section>
    <section className="demo-section"><div className="shell"><div className="demo-section__heading"><div><span className="eyebrow">UNA SOLUCIÓN CONECTADA</span><h2>La venta continúa después del primer clic.</h2></div><p>Proponemos empezar con un número oficial, Yaku como CRM y un piloto medible. El panel DMS es la alternativa si OLBOL prefiere un CRM propio.</p></div><div className="proposal-pillars">{pillars.map(item=><article key={item.number}><div><item.icon size={21}/><span>{item.number}</span></div><h3>{item.title}</h3><p>{item.copy}</p></article>)}</div></div></section>
    <section className="demo-section demo-section--dark" id="whatsapp"><div className="shell"><div className="demo-section__heading"><div><span className="eyebrow">WHATSAPP PARA VENTAS Y ANUNCIOS</span><h2>Un canal oficial. Una operación cuidada.</h2></div><ShieldCheck size={24}/></div><div className="whatsapp-plan"><div><h3>La solución que proponemos</h3><p>Conectar WhatsApp Business Platform con Yaku y un asesor de IA centrado en el catálogo de OLBOL. Recomendamos Meta Cloud API directa si la integración es viable; también evaluamos Twilio o 360dialog. El vendedor puede tomar el control de la conversación.</p><Link href="/crm" className="feature-vehicle__link">Ver el seguimiento comercial <ArrowRight size={16}/></Link></div><ol>{["Cuenta, número y activos de Meta a nombre de OLBOL.","Permiso explícito para seguimiento y promociones; registrar fecha y origen.","Plantillas aprobadas para contactos iniciados por la empresa; respetar la ventana de atención de 24 horas.","Baja sencilla y revisión de calidad, reportes y restricciones antes de aumentar envíos.","Escalamiento a una persona y pausa de campañas si baja la calidad."].map((text,i)=><li key={text}><span>0{i+1}</span><p>{text}</p><Check size={16}/></li>)}</ol></div><p className="whatsapp-plan__note">La plataforma oficial es la vía autorizada para esta integración. Las conexiones no oficiales, como automatizar WhatsApp Web fuera de los canales de Meta, añaden riesgo de bloqueo. En todos los casos se deben cumplir las políticas de WhatsApp.</p></div></section>
    <section className="demo-section demo-section--soft"><div className="shell"><div className="demo-section__heading"><div><span className="eyebrow">ELEGIR CÓMO CONECTARNOS</span><h2>El CRM y el canal son decisiones distintas.</h2></div><p>Las tres rutas usan la plataforma oficial. Nuestro asesor y la atención humana se integran con Yaku o con el panel DMS.</p></div><div className="proposal-pillars channel-options">{whatsappOptions.map(option=><article key={option.id}><span>{option.label}</span><h3>{option.name}</h3><p>{option.copy}</p></article>)}</div><p className="demo-note">La app Business por sí sola no ofrece nuestra integración personalizada de IA y CRM. La coexistencia con la API depende de la elegibilidad del número y del flujo del proveedor.</p></div></section>
    <section className="demo-section" id="solucion"><div className="shell"><div className="demo-section__heading"><div><span className="eyebrow">SEGUIMIENTO COMERCIAL</span><h2>Una solución que acompaña a tu equipo.</h2></div><p>El asesor responde las consultas iniciales y el vendedor continúa con el contexto. Elegimos el CRM que mejor se adapte a la operación de OLBOL.</p></div><div className="proposal-pillars crm-options"><article><div><Users size={21}/><span>PRIMERA OPCIÓN</span></div><h3>Yaku</h3><p>Nuestra plataforma CRM para centralizar contactos, conversaciones y oportunidades. Validamos sus capacidades de integración y definimos responsables, etapas y próximas acciones con OLBOL.</p></article><article><div><Database size={21}/><span>ALTERNATIVA</span></div><h3>CRM en el panel DMS</h3><p>Un panel propio con contactos, responsables, etapas e historial. Definimos el alcance de la bandeja de atención para que el vendedor pueda recibir la conversación y tomar el control de la IA.</p></article></div><p className="demo-note">El equipo comercial coordina el alcance, las condiciones y los siguientes pasos del piloto con OLBOL.</p></div></section>
    <section className="demo-section demo-section--soft"><div className="shell"><div className="demo-section__heading"><div><span className="eyebrow">DEL PILOTO A LA OPERACIÓN</span><h2>Primero conectar. Después medir y mejorar.</h2></div><p>Calendario propuesto de 4–6 semanas desde la entrega de accesos, catálogo y materiales.</p></div><div className="roadmap-grid">{[
      ["01","SEMANA 1","Preparar","Catálogo real, número y activos de Meta. Validar capacidades de Yaku, embudo y alcance del piloto."],
      ["02","SEMANAS 2–3","Conectar","Web y asesor al catálogo. WhatsApp oficial y conexión con Yaku o el CRM del DMS según el alcance acordado."],
      ["03","SEMANA 4","Probar","Una campaña piloto, seguimiento, plantillas y capacitación de vendedores."],
      ["04","SEMANAS 5–6","Ajustar","Validar el flujo completo y medir respuesta, citas y oportunidades por origen."],
    ].map(([number,label,title,copy])=><article className="roadmap-card" key={number}><div className="roadmap-card__top"><span>{number}</span><span>Propuesto</span></div><span className="eyebrow">{label}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="demo-note">Verificación de empresa, aprobación de número y plantillas dependen de Meta. El calendario se ajusta a esas aprobaciones y a la auditoría de Yaku. Un CRM propio requiere confirmar alcance y plazo. Financiamiento bancario, pagos y reservas reales requieren una fase adicional.</p></div></section>
    <section className="demo-section demo-section--dark"><div className="shell"><div className="demo-section__heading"><div><span className="eyebrow">RESPUESTAS PARA LA REUNIÓN</span><h2>Las decisiones importantes, sin letra pequeña.</h2></div><Sparkles size={20}/></div><div className="answer-grid">{answers.map(item=><article className="answer-card" key={item.question}><span>{item.tag}</span><h3>{item.question}</h3><p>{item.answer}</p></article>)}</div></div></section>
    <section className="demo-section"><div className="shell demo-explainer"><div><span className="eyebrow">MEDIR LO QUE AYUDA A VENDER</span><h2>Una consulta tiene valor cuando avanza.</h2><p>Durante el piloto medimos tiempo de primera respuesta, oportunidades calificadas, pruebas agendadas y cierres por campaña. La mejora se compara con la situación inicial de OLBOL.</p></div><div className="system-flow"><div><Database size={19}/><span>Catálogo real</span></div><i>→</i><div><Sparkles size={19}/><span>Asesor</span></div><i>→</i><div><MessageCircle size={19}/><span>WhatsApp</span></div><i>→</i><div><Users size={19}/><span>Yaku o CRM DMS</span></div></div></div></section>
    <section className="proposal-sources"><div className="shell"><span className="eyebrow">RESEARCH · 2 DE OCTUBRE DE 2026</span><h3>Fuentes y condiciones verificadas</h3><p>La solución se apoya en WhatsApp Business Platform, atención humana y seguimiento comercial. La coexistencia de la app y la API depende de la elegibilidad del número y del proceso de alta. Verificamos estos requisitos antes de conectar el canal de OLBOL.</p><div>{researchSources.map(source=><a href={source.url} key={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a>)}</div></div></section>
    <section className="demo-cta"><div className="shell"><div><span className="eyebrow">LA DECISIÓN QUE PROPONEMOS</span><h2>Empezar con un piloto y un objetivo claro.</h2></div><Link href="/crm" className="button-primary">Ver la operación comercial <ArrowRight size={16}/></Link></div></section>
  </main>;
}
