import Link from "next/link";
import { ArrowRight, Check, Database, MessageCircle, ShieldCheck, Sparkles, Users, Megaphone } from "lucide-react";
import { ProposalCosts } from "@/components/proposal-costs";
import { researchSources } from "@/domain/proposal";

const pillars = [
  { icon: Megaphone, number: "01", title: "Atraer con intención", copy: "Anuncios en Facebook e Instagram que invitan al cliente a escribir a OLBOL. Registramos el origen para medir qué campañas producen oportunidades." },
  { icon: MessageCircle, number: "02", title: "Responder con contexto", copy: "WhatsApp Business oficial y un asesor que consulta el catálogo. El equipo toma el control cuando la decisión necesita atención humana." },
  { icon: Users, number: "03", title: "Dar seguimiento", copy: "Un CRM simple: cada oportunidad tiene responsable, etapa, próxima acción y un historial. Así una buena conversación puede avanzar hacia una venta." },
];
const answers = [
  { question: "¿Nos pueden garantizar que no bloqueen la cuenta?", answer: "No existe garantía de cero bloqueos. Proponemos reducir el riesgo con el canal oficial, permisos registrados, plantillas aprobadas, bajas inmediatas y revisión de la calidad de la cuenta.", tag: "Un compromiso responsable" },
  { question: "¿Qué pasa con el número que ya utiliza OLBOL?", answer: "Primero revisamos el estado del número y sus antecedentes. Evaluamos la coexistencia de la app y la API con el proveedor; si no es elegible, acordamos una migración antes de tocar el canal actual.", tag: "Continuidad del negocio" },
  { question: "¿Qué hace el CRM básico?", answer: "Centraliza contactos y contexto, asigna vendedores, ordena etapas, programa tareas y muestra el origen de cada oportunidad. Recomendamos Kommo Advanced para incluir automatizaciones desde el inicio.", tag: "Una operación simple" },
  { question: "¿Qué incluye realmente esta demo?", answer: "Catálogo conceptual, asesor local, comparación, simulación de cuota, resumen de WhatsApp y consola CRM con datos ficticios. La conexión oficial, el inventario real y las campañas se implementan en el piloto.", tag: "Alcance claro" },
];

export default function DemoPage() {
  return <main className="demo-page">
    <section className="demo-hero"><div className="shell demo-hero__inner"><div><span className="demo-kicker"><span/> OLBOL / PROPUESTA COMERCIAL</span><h1>Más conversaciones. Mejor seguimiento.</h1><p>Una experiencia que conecta tu catálogo, WhatsApp y equipo comercial para acompañar al cliente desde el primer interés.</p><div className="demo-hero__actions"><Link href="/asesor" className="button-primary">Probar la experiencia <ArrowRight size={16}/></Link><a href="#costos" className="button-light">Revisar la inversión <ArrowRight size={16}/></a></div></div><div className="demo-hero__signal"><div className="demo-hero__signal-top"><span>PROPUESTA PARA OLBOL</span><span className="signal-dot"/></div><strong>De un anuncio a una oportunidad con responsable.</strong><div className="demo-hero__signal-line"><span/><span/><span/><span/></div><small>Demostración conceptual · Integración oficial en el piloto</small></div></div></section>
    <section className="demo-section"><div className="shell"><div className="demo-section__heading"><div><span className="eyebrow">UNA SOLUCIÓN CONECTADA</span><h2>La venta continúa después del primer clic.</h2></div><p>Proponemos empezar con un número oficial, tres usuarios del CRM y un piloto medible.</p></div><div className="proposal-pillars">{pillars.map(item=><article key={item.number}><div><item.icon size={21}/><span>{item.number}</span></div><h3>{item.title}</h3><p>{item.copy}</p></article>)}</div></div></section>
    <section className="demo-section demo-section--dark" id="whatsapp"><div className="shell"><div className="demo-section__heading"><div><span className="eyebrow">WHATSAPP PARA VENTAS Y ANUNCIOS</span><h2>Un canal oficial. Una operación cuidada.</h2></div><ShieldCheck size={24}/></div><div className="whatsapp-plan"><div><h3>La solución que proponemos</h3><p>Conectar WhatsApp Business Platform mediante la integración oficial de Kommo. Los anuncios Click to WhatsApp abren conversaciones iniciadas por el comprador; el asesor y el vendedor mantienen el contexto dentro del CRM.</p><Link href="/crm" className="feature-vehicle__link">Ver el seguimiento comercial <ArrowRight size={16}/></Link></div><ol>{["Cuenta, número y activos de Meta a nombre de OLBOL.","Permiso explícito para seguimiento y promociones; registrar fecha y origen.","Plantillas aprobadas para contactos iniciados por la empresa; respetar la ventana de atención de 24 horas.","Baja sencilla y revisión de calidad, reportes y restricciones antes de aumentar envíos.","Escalamiento a una persona y pausa de campañas si baja la calidad."].map((text,i)=><li key={text}><span>0{i+1}</span><p>{text}</p><Check size={16}/></li>)}</ol></div><p className="whatsapp-plan__note">La API oficial reduce riesgos operativos; Meta puede restringir cuentas por incumplimiento. No proponemos automatizaciones de WhatsApp Web ni envíos a bases sin consentimiento.</p></div></section>
    <section className="demo-section" id="costos"><div className="shell"><div className="demo-section__heading"><div><span className="eyebrow">INVERSIÓN TRANSPARENTE</span><h2>Un punto de partida, con los costos a la vista.</h2></div><p>Propuesta orientativa en USD. Separa nuestros honorarios de la licencia, consumo y publicidad.</p></div><ProposalCosts/></div></section>
    <section className="demo-section demo-section--soft"><div className="shell"><div className="demo-section__heading"><div><span className="eyebrow">DEL PILOTO A LA OPERACIÓN</span><h2>Primero conectar. Después medir y mejorar.</h2></div><p>Calendario propuesto de 4–6 semanas desde la entrega de accesos, catálogo y materiales.</p></div><div className="roadmap-grid">{[
      ["01","SEMANA 1","Preparar","Catálogo real, número, activos de Meta, permisos y definición del embudo."],
      ["02","SEMANAS 2–3","Conectar","Web y asesor al catálogo. WhatsApp oficial, CRM y tareas comerciales."],
      ["03","SEMANA 4","Probar","Una campaña piloto, seguimiento, plantillas y capacitación de vendedores."],
      ["04","SEMANAS 5–6","Ajustar","Validar el flujo completo y medir respuesta, citas y oportunidades por origen."],
    ].map(([number,label,title,copy])=><article className="roadmap-card" key={number}><div className="roadmap-card__top"><span>{number}</span><span>Propuesto</span></div><span className="eyebrow">{label}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="demo-note">Verificación de empresa, aprobación de número y plantillas dependen de Meta. El calendario se ajusta a esas aprobaciones. Financiamiento bancario, pagos y reservas reales requieren una fase adicional.</p></div></section>
    <section className="demo-section demo-section--dark"><div className="shell"><div className="demo-section__heading"><div><span className="eyebrow">RESPUESTAS PARA LA REUNIÓN</span><h2>Las decisiones importantes, sin letra pequeña.</h2></div><Sparkles size={20}/></div><div className="answer-grid">{answers.map(item=><article className="answer-card" key={item.question}><span>{item.tag}</span><h3>{item.question}</h3><p>{item.answer}</p></article>)}</div></div></section>
    <section className="demo-section"><div className="shell demo-explainer"><div><span className="eyebrow">MEDIR LO QUE AYUDA A VENDER</span><h2>Una consulta tiene valor cuando avanza.</h2><p>Durante el piloto medimos tiempo de primera respuesta, oportunidades calificadas, pruebas agendadas y cierres por campaña. La mejora se compara con la situación inicial de OLBOL.</p></div><div className="system-flow"><div><Database size={19}/><span>Catálogo real</span></div><i>→</i><div><Sparkles size={19}/><span>Asesor</span></div><i>→</i><div><MessageCircle size={19}/><span>WhatsApp</span></div><i>→</i><div><Users size={19}/><span>CRM</span></div></div></div></section>
    <section className="proposal-sources"><div className="shell"><span className="eyebrow">RESEARCH · 2 DE OCTUBRE DE 2026</span><h3>Fuentes y condiciones verificadas</h3><p>Kommo publica nuevas tarifas y cambios de mensajería para octubre de 2026. La página general de Meta mantiene referencias a mensajes de atención gratis: confirmar el tarifario aplicable del número antes de cotizar consumo. La provisión de WhatsApp contempla cargos variables y no promete atención ilimitada gratuita.</p><div>{researchSources.map(source=><a href={source.url} key={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a>)}</div></div></section>
    <section className="demo-cta"><div className="shell"><div><span className="eyebrow">LA DECISIÓN QUE PROPONEMOS</span><h2>Empezar con un piloto y un objetivo claro.</h2></div><Link href="/crm" className="button-primary">Ver la operación comercial <ArrowRight size={16}/></Link></div></section>
  </main>;
}
