import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { notFound } from "next/navigation";
import { VehicleDetailActions } from "@/components/vehicle-detail-actions";
import { VehicleGallery } from "@/components/vehicle-gallery";
import { formatPrice, getVehicleBySlug, vehicles } from "@/domain/vehicles";

export function generateStaticParams() { return vehicles.map((vehicle) => ({ slug: vehicle.slug })); }

export default async function VehiclePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const vehicle = getVehicleBySlug(slug);
  if (!vehicle) notFound();
  return <main><div className="shell vehicle-detail"><div className="breadcrumbs"><Link href="/vehiculos">Vehículos</Link><span>/</span><span>{vehicle.name}</span></div><section className="detail-hero"><div className="detail-hero__visual"><VehicleGallery vehicle={vehicle} /></div><div className="detail-hero__content"><div className="eyebrow-row"><span className="eyebrow">{vehicle.eyebrow}</span><span className="availability-dot" data-tone={vehicle.availability}>{vehicle.conditionLabel}</span></div><h1>{vehicle.name}</h1><p>{vehicle.tagline}</p><div className="detail-price"><span>Precio final demo</span>{formatPrice(vehicle.priceUsd)}</div><VehicleDetailActions vehicle={vehicle} /><div className="detail-trust"><span>✓ Precio visible</span><span>✓ Datos de catálogo</span><span>✓ Atención por WhatsApp</span></div></div></section><div className="detail-metrics"><div><strong>{vehicle.rangeKm} km</strong><span>Autonomía estimada</span></div><div><strong>{vehicle.powerKw} kW</strong><span>Potencia máxima</span></div><div><strong>{vehicle.fastChargeMinutes} min</strong><span>Carga rápida</span></div><div><strong>{vehicle.passengers}</strong><span>Pasajeros</span></div></div><section className="spec-section"><div><span className="eyebrow">FICHA TÉCNICA</span><h2>Lo que mueve esta experiencia.</h2></div><div className="spec-table"><div><span>Motor</span><strong>{vehicle.engine}</strong></div><div><span>Transmisión</span><strong>{vehicle.transmission}</strong></div><div><span>Combustible</span><strong>{vehicle.fuel}</strong></div><div><span>Año</span><strong>{vehicle.year}</strong></div><div><span>Kilometraje</span><strong>{vehicle.mileageKm.toLocaleString("es-BO")} km</strong></div><div><span>Condición</span><strong>{vehicle.conditionLabel}</strong></div></div></section><section className="detail-story"><div><span className="eyebrow">PENSADO PARA TU DÍA</span><h2>La tecnología desaparece. La experiencia queda.</h2></div><div className="detail-story__copy"><p>{vehicle.name} combina una respuesta eléctrica inmediata con una cabina serena y flexible. Todo está donde esperas, justo cuando lo necesitas.</p><p>Este es un concepto de producto para la demo OLBOL. Las configuraciones, precios y disponibilidad finales se definirán junto al equipo de la marca.</p><div className="feature-list">{vehicle.features.map((feature) => <span key={feature}>↗ {feature}</span>)}</div><Link href="/asesor" className="feature-vehicle__link">Preguntar al asesor <ArrowRight size={16} /></Link></div></section></div></main>;
}
