const { chromium } = require(process.env.OLBOL_RUNTIME_MODULES + '/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
async function main() {
  const browser = await chromium.launch({headless:true,channel:'msedge'});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const checks=[];
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const goto=async route=>{await page.goto('http://localhost:3000'+route,{waitUntil:'domcontentloaded',timeout:180000});await page.locator('html[data-experience-ready="true"]').waitFor({timeout:120000});};
  const check=(name,condition)=>{assert.ok(condition,name);checks.push(name);console.log(name);};
  await goto('/vehiculos');
  await page.getByRole('textbox',{name:'Buscar modelo'}).fill('imposible');
  await page.getByText('No encontramos un modelo con esos filtros.').waitFor();
  await page.getByRole('button',{name:'Ver todo el catálogo'}).click();
  check('Filtros y recuperación de catálogo vacío',await page.locator('.vehicle-card').count()===3);
  await goto('/vehiculos/terra-s5');
  await page.getByRole('button',{name:'Ampliar imagen'}).click();
  check('Galería ampliable',await page.getByRole('dialog').count()===1);
  await page.keyboard.press('Escape');
  check('Cierre por Escape y restauración de foco',await page.getByRole('button',{name:'Ampliar imagen'}).evaluate(e=>document.activeElement===e));
  await page.getByRole('button',{name:'Agendar prueba de manejo'}).click();
  await page.getByRole('textbox',{name:'Nombre',exact:true}).fill('Cliente Demo');
  await page.getByRole('textbox',{name:'Teléfono'}).fill('70000000');
  await page.getByRole('textbox',{name:'Correo'}).fill('demo@example.com');
  await page.locator('input[name="date"]').fill('2027-01-15');
  await page.getByRole('button',{name:'Solicitar prueba',exact:true}).click();
  await page.getByRole('heading',{name:'Solicitud de prueba simulada.'}).waitFor();
  await page.keyboard.press('Escape');checks.push('Prueba de manejo simulada');
  // Simulate a network failure for the advisor: the local engine must keep the sale moving.
  await page.route('**/api/advisor',route=>route.abort());
  await goto('/asesor');
  await page.getByRole('button',{name:'Reiniciar demo'}).click();
  const send=async message=>{await page.getByRole('textbox',{name:'Mensaje para el asesor'}).fill(message);await page.getByRole('button',{name:'Enviar mensaje'}).click();await page.getByRole('textbox',{name:'Mensaje para el asesor'}).waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('.advisor-composer input').disabled);};
  await send('Somos 5, viajamos los fines de semana y tengo un presupuesto de USD 30 mil');
  await page.getByText('MI RECOMENDACIÓN',{exact:true}).waitFor();checks.push('Recomendación y fallback sin red');
  await page.screenshot({path:'docs/capturas/recomendacion-escena.png'});
  await send('Quiero comparar');await page.locator('.comparison-table-wrap').waitFor();
  await send('Quiero cotizar');await page.locator('.quote-panel').waitFor();
  check('Comparación cambia a cotización',await page.locator('.comparison-table-wrap').count()===0);
  await page.getByRole('button',{name:'Validar cotización',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('.quote-button').disabled);
  check('Validación de cotización',await page.locator('.quote-panel .form-error').count()===0);
  await page.getByRole('button',{name:'Preparar continuidad',exact:true}).click();
  await page.locator('.whatsapp-card__message').waitFor();
  check('Resumen WhatsApp conserva el contexto',(await page.locator('.whatsapp-card__message').innerText()).includes('Terra S5'));
  await page.screenshot({path:'docs/capturas/cotizacion.png',fullPage:true});
  const quoteBox=await page.locator('.quote-panel').boundingBox();
  const whatsappBox=await page.locator('.whatsapp-card').boundingBox();
  await page.screenshot({path:'docs/capturas/cotizacion-escena.png',clip:{x:quoteBox.x,y:quoteBox.y,width:quoteBox.width,height:whatsappBox.y+whatsappBox.height-quoteBox.y}});
  await page.reload({waitUntil:'domcontentloaded'});await page.locator('.quote-panel').waitFor({timeout:60000});checks.push('Cotización persiste al recargar');
  await send('Me interesa');await page.locator('.interest-card').waitFor();
  await goto('/crm');await page.locator('.crm-board').waitFor();
  await page.getByRole('button').filter({hasText:'Visitante web · demo'}).click();
  await page.getByRole('button',{name:'Responsable',exact:true}).click();await page.getByRole('option',{name:'Sofía',exact:true}).click();
  await page.getByRole('button',{name:'Etapa comercial',exact:true}).click();await page.getByRole('option',{name:'Prueba',exact:true}).click();
  await page.getByRole('textbox',{name:'Nueva nota de ejemplo'}).fill('Confirmar disponibilidad con OLBOL.');await page.getByRole('button',{name:'Guardar nota'}).click();
  await page.getByText('Confirmar disponibilidad con OLBOL.',{exact:true}).waitFor();await page.keyboard.press('Escape');checks.push('Interés web → CRM → asignación, etapa y nota');
  await page.reload({waitUntil:'domcontentloaded'});await page.locator('.crm-board').waitFor();
  const lead=page.getByRole('button').filter({hasText:'Visitante web · demo'});
  check('Seguimiento CRM persiste al recargar',(await lead.innerText()).includes('Sofía'));
  await goto('/demo');
  const initial=await page.locator('.cost-total strong').innerText();
  await page.locator('#sellers').fill('5');
  check('Presupuesto se ajusta al tamaño del equipo',initial!==await page.locator('.cost-total strong').innerText());
  await goto('/comparar');await page.getByRole('button',{name:'Primer vehículo',exact:true}).click();await page.getByRole('option',{name:'Alto X7',exact:true}).click();
  check('Comparador seleccionable',(await page.locator('.comparison-vehicles').innerText()).includes('Alto X7'));
  await page.setViewportSize({width:390,height:844});await goto('/');
  await page.getByRole('button',{name:'Abrir menú',exact:true}).click();check('Menú móvil accesible',await page.getByRole('navigation').isVisible());await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Ver continuidad por WhatsApp'}).click();await page.getByRole('heading',{name:'Una conversación que continúa.'}).waitFor();await page.keyboard.press('Escape');checks.push('WhatsApp demo y menú móvil');
  check('Sin errores de ejecución en navegador',errors.length===0);
  fs.writeFileSync('docs/verificacion-funcional.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors}));await browser.close();
}
main().catch(e=>{console.error(e);process.exit(1);});
